apiVersion: apps/v1
kind: Deployment
metadata:
  name: kejizhang-app
  labels:
    app: kejizhang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kejizhang
  template:
    metadata:
      labels:
        app: kejizhang
    spec:
      containers:
      - name: kejizhang
        image: kejizhang:latest  # 需要替换为您的镜像地址
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: kejizhang-secrets
              key: supabase-url
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: kejizhang-secrets
              key: supabase-anon-key
        - name: NEXT_PUBLIC_OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: kejizhang-secrets
              key: openrouter-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: kejizhang-service
spec:
  selector:
    app: kejizhang
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kejizhang-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - your-domain.com  # 替换为您的域名
    secretName: kejizhang-tls
  rules:
  - host: your-domain.com  # 替换为您的域名
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kejizhang-service
            port:
              number: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: kejizhang-secrets
type: Opaque
data:
  # 注意：以下值需要进行 base64 编码
  # 使用命令：echo -n "your-value" | base64
  supabase-url: # base64 encoded value
  supabase-anon-key: # base64 encoded value  
  openrouter-api-key: # base64 encoded value 